### ISSUE TITLE
✏ Request to add more reusable comps like UI Kits 💻 📱

### ISSUE THREAD

**Issue by Maddoxx88** [vadimdemedes/excalidraw-ui#1]
UI Kits for Mobile and Web

**Comment by Maddoxx88** [comment]
I'm ready with some, can I start a PR?

**Comment by Maddoxx88** [comment]
I'm ready with some, can I start a PR? @vadimdemedes

**Comment by vadimdemedes** [comment]
Of course, go ahead and we can discuss in the PR.
